### ISSUE TITLE
set inspec_version: ">= 4.0"

### ISSUE THREAD

**Issue by ejaronne** [mitre/oracle-java-runtime-environment-7-unix-stig-baseline#4]
or inspec_version: ">= 3.0"

**Comment by Amndeep7** [comment]
https://github.com/mitre/oracle-java-runtime-environment-7-unix-stig-baseline/blob/0f444733c1fdafdde5206988664ecf946a590da2/inspec.yml#L9

seems to be implemented.  please reopen if necessary @ejaronne
